DEFAULT_PAGE_SIZE = 12
SKILL_SEARCH_LIMIT = 10

GITHUB_HOSTS = {
    "github.com",
    "www.github.com",
}

USER_FIELD_MAX_LENGTH = 124
SKILL_NAME_MAX_LENGTH = USER_FIELD_MAX_LENGTH
PHONE_MAX_LENGTH = 12
ABOUT_MAX_LENGTH = 256

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

AVATAR_SIZE = 200
AVATAR_BACKGROUND = "#4A90E2"
AVATAR_TEXT_COLOR = "#FFFFFF"
AVATAR_FONT_SIZE = 100
AVATAR_VERTICAL_OFFSET = 10
