DEFAULT_PAGE_SIZE = 12
GITHUB_HOSTS = {"github.com", "www.github.com"}

USER_FIELD_MAX_LENGTH = 124
SKILL_NAME_MAX_LENGTH = USER_FIELD_MAX_LENGTH
PHONE_MAX_LENGTH = 12
ABOUT_MAX_LENGTH = 256

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
SKILL_SEARCH_LIMIT = 10
